# Auto-generated by asn1ate v.0.6.0 from Msg.asn1
# (last modified on 2023-03-28 16:59:45.358123)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class Mensagem(univ.Sequence):
    pass


Mensagem.componentType = namedtype.NamedTypes(
    namedtype.NamedType('tipo', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('id', char.PrintableString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 16)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('valor', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


